language: java


gemfile:
  - gemfiles/Gemfile.rails-2.3.x
  - gemfiles/Gemfile.rails-3.0.x

before_install:
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y
  - gem install bundler


install:
  - bundle init
  - bundle install

script:
  - mvn clean install
  - mvn compile
  - mvn package
  - java -jar target/studentapp-0.0.1-SNAPSHOT.jar &

